// generated by Go Code Generator(https://github.com/OhYee/gcg); DO NOT EDIT

package transfer

import (
	"fmt"
)

// FromValue from a build-in type value to bytes
func FromValue(value any) (b []byte, err error) {
	switch value.(type) {

	case uint8:
		v, _ := value.(uint8)
		b, err = FromUint8(v)

	case uint16:
		v, _ := value.(uint16)
		b, err = FromUint16(v)

	case uint32:
		v, _ := value.(uint32)
		b, err = FromUint32(v)

	case uint64:
		v, _ := value.(uint64)
		b, err = FromUint64(v)

	case int8:
		v, _ := value.(int8)
		b, err = FromInt8(v)

	case int16:
		v, _ := value.(int16)
		b, err = FromInt16(v)

	case int32:
		v, _ := value.(int32)
		b, err = FromInt32(v)

	case int64:
		v, _ := value.(int64)
		b, err = FromInt64(v)

	default:
		err = fmt.Errorf("Transfer Error: Can not solve the unknown type: %T", value)
	}
	return
}
