name: master
on: [push]
jobs:

  build:
    name: master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - run:   go test ./... -v 